export const MapBoxApi = 'pk.eyJ1IjoiaGFyaW9tb2poYTIzIiwiYSI6ImNsY2h1OTJvbDAxemwzenFoNWlmaGdkZ2kifQ.fSjUN1HP6aJZ4D_5JgA-Yw'
export const MapBoxOutdoorsStyle = 'mapbox://styles/mapbox/outdoors-v12?optimize=true'
export const MapBoxStreetStyle = 'mapbox://styles/mapbox/streets-v12?optimize=true'
export const MapBoxDarkStyle = 'mapbox://styles/mapbox/dark-v11?optimize=true'
export const MapBoxSatelliteStyle = 'mapbox://styles/mapbox/satellite-v9?optimize=true'
export const MapBoxSatelliteStretStyle = 'mapbox://styles/mapbox/satellite-streets-v12?optimize=true'
export const MapBoxNavigationNight = 'mapbox://styles/mapbox/navigation-night-v1'
