export const MapBoxApi = 'pk.eyJ1IjoiaGFyaW9tb2poYTIzIiwiYSI6ImNsY2h1OTJvbDAxemwzenFoNWlmaGdkZ2kifQ.fSjUN1HP6aJZ4D_5JgA-Yw'
export const MapBoxOutdoorsStyle = 'mapbox://styles/mapbox/outdoors-v12'
export const MapBoxStreetStyle = 'mapbox://styles/mapbox/streets-v12'
export const MapBoxDarkStyle = 'mapbox://styles/mapbox/dark-v11'
export const MapBoxSatelliteStyle = 'mapbox://styles/mapbox/satellite-v9'
export const MapBoxSatelliteStretStyle = 'mapbox://styles/mapbox/satellite-streets-v12'
